## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Right Bite"
theme = "hugo-story"
baseURL = "/"
languageCode = "en-us"

## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]
# googleAnalytics = "your-google-analytics-id"


## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  favicon = true

[Params.social]
  email = "fk.dvizhenie@yandex.ru"